# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from camera_monitoring/MsgStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MsgStatus(genpy.Message):
  _md5sum = "9a60217041610aa06a277c2abf60970c"
  _type = "camera_monitoring/MsgStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool running
bool laser_on
float32 speed
float32 power
"""
  __slots__ = ['running','laser_on','speed','power']
  _slot_types = ['bool','bool','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       running,laser_on,speed,power

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MsgStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.running is None:
        self.running = False
      if self.laser_on is None:
        self.laser_on = False
      if self.speed is None:
        self.speed = 0.
      if self.power is None:
        self.power = 0.
    else:
      self.running = False
      self.laser_on = False
      self.speed = 0.
      self.power = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B2f().pack(_x.running, _x.laser_on, _x.speed, _x.power))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.running, _x.laser_on, _x.speed, _x.power,) = _get_struct_2B2f().unpack(str[start:end])
      self.running = bool(self.running)
      self.laser_on = bool(self.laser_on)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B2f().pack(_x.running, _x.laser_on, _x.speed, _x.power))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.running, _x.laser_on, _x.speed, _x.power,) = _get_struct_2B2f().unpack(str[start:end])
      self.running = bool(self.running)
      self.laser_on = bool(self.laser_on)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B2f = None
def _get_struct_2B2f():
    global _struct_2B2f
    if _struct_2B2f is None:
        _struct_2B2f = struct.Struct("<2B2f")
    return _struct_2B2f
