// Generated by gencpp from file camera_monitoring/MsgAcceleration.msg
// DO NOT EDIT!


#ifndef CAMERA_MONITORING_MESSAGE_MSGACCELERATION_H
#define CAMERA_MONITORING_MESSAGE_MSGACCELERATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace camera_monitoring
{
template <class ContainerAllocator>
struct MsgAcceleration_
{
  typedef MsgAcceleration_<ContainerAllocator> Type;

  MsgAcceleration_()
    : header()
    , acceleration(0.0)
    , acceleration_averaged(0.0)  {
    }
  MsgAcceleration_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , acceleration(0.0)
    , acceleration_averaged(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _acceleration_type;
  _acceleration_type acceleration;

   typedef float _acceleration_averaged_type;
  _acceleration_averaged_type acceleration_averaged;





  typedef boost::shared_ptr< ::camera_monitoring::MsgAcceleration_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_monitoring::MsgAcceleration_<ContainerAllocator> const> ConstPtr;

}; // struct MsgAcceleration_

typedef ::camera_monitoring::MsgAcceleration_<std::allocator<void> > MsgAcceleration;

typedef boost::shared_ptr< ::camera_monitoring::MsgAcceleration > MsgAccelerationPtr;
typedef boost::shared_ptr< ::camera_monitoring::MsgAcceleration const> MsgAccelerationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_monitoring::MsgAcceleration_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_monitoring::MsgAcceleration_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::camera_monitoring::MsgAcceleration_<ContainerAllocator1> & lhs, const ::camera_monitoring::MsgAcceleration_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.acceleration == rhs.acceleration &&
    lhs.acceleration_averaged == rhs.acceleration_averaged;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::camera_monitoring::MsgAcceleration_<ContainerAllocator1> & lhs, const ::camera_monitoring::MsgAcceleration_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace camera_monitoring

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::camera_monitoring::MsgAcceleration_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_monitoring::MsgAcceleration_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_monitoring::MsgAcceleration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_monitoring::MsgAcceleration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_monitoring::MsgAcceleration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_monitoring::MsgAcceleration_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_monitoring::MsgAcceleration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "47cc82a8c8063d6c8db25dce71da2cbc";
  }

  static const char* value(const ::camera_monitoring::MsgAcceleration_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x47cc82a8c8063d6cULL;
  static const uint64_t static_value2 = 0x8db25dce71da2cbcULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_monitoring::MsgAcceleration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_monitoring/MsgAcceleration";
  }

  static const char* value(const ::camera_monitoring::MsgAcceleration_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_monitoring::MsgAcceleration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 acceleration\n"
"float32 acceleration_averaged\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::camera_monitoring::MsgAcceleration_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_monitoring::MsgAcceleration_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.acceleration);
      stream.next(m.acceleration_averaged);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgAcceleration_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_monitoring::MsgAcceleration_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_monitoring::MsgAcceleration_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "acceleration: ";
    Printer<float>::stream(s, indent + "  ", v.acceleration);
    s << indent << "acceleration_averaged: ";
    Printer<float>::stream(s, indent + "  ", v.acceleration_averaged);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MONITORING_MESSAGE_MSGACCELERATION_H
