// Generated by gencpp from file camera_monitoring/MsgStatus.msg
// DO NOT EDIT!


#ifndef CAMERA_MONITORING_MESSAGE_MSGSTATUS_H
#define CAMERA_MONITORING_MESSAGE_MSGSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera_monitoring
{
template <class ContainerAllocator>
struct MsgStatus_
{
  typedef MsgStatus_<ContainerAllocator> Type;

  MsgStatus_()
    : running(false)
    , laser_on(false)
    , speed(0.0)
    , power(0.0)  {
    }
  MsgStatus_(const ContainerAllocator& _alloc)
    : running(false)
    , laser_on(false)
    , speed(0.0)
    , power(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _running_type;
  _running_type running;

   typedef uint8_t _laser_on_type;
  _laser_on_type laser_on;

   typedef float _speed_type;
  _speed_type speed;

   typedef float _power_type;
  _power_type power;





  typedef boost::shared_ptr< ::camera_monitoring::MsgStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_monitoring::MsgStatus_<ContainerAllocator> const> ConstPtr;

}; // struct MsgStatus_

typedef ::camera_monitoring::MsgStatus_<std::allocator<void> > MsgStatus;

typedef boost::shared_ptr< ::camera_monitoring::MsgStatus > MsgStatusPtr;
typedef boost::shared_ptr< ::camera_monitoring::MsgStatus const> MsgStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_monitoring::MsgStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_monitoring::MsgStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::camera_monitoring::MsgStatus_<ContainerAllocator1> & lhs, const ::camera_monitoring::MsgStatus_<ContainerAllocator2> & rhs)
{
  return lhs.running == rhs.running &&
    lhs.laser_on == rhs.laser_on &&
    lhs.speed == rhs.speed &&
    lhs.power == rhs.power;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::camera_monitoring::MsgStatus_<ContainerAllocator1> & lhs, const ::camera_monitoring::MsgStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace camera_monitoring

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::camera_monitoring::MsgStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_monitoring::MsgStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_monitoring::MsgStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_monitoring::MsgStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_monitoring::MsgStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_monitoring::MsgStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_monitoring::MsgStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9a60217041610aa06a277c2abf60970c";
  }

  static const char* value(const ::camera_monitoring::MsgStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9a60217041610aa0ULL;
  static const uint64_t static_value2 = 0x6a277c2abf60970cULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_monitoring::MsgStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_monitoring/MsgStatus";
  }

  static const char* value(const ::camera_monitoring::MsgStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_monitoring::MsgStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool running\n"
"bool laser_on\n"
"float32 speed\n"
"float32 power\n"
;
  }

  static const char* value(const ::camera_monitoring::MsgStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_monitoring::MsgStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.running);
      stream.next(m.laser_on);
      stream.next(m.speed);
      stream.next(m.power);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_monitoring::MsgStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_monitoring::MsgStatus_<ContainerAllocator>& v)
  {
    s << indent << "running: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.running);
    s << indent << "laser_on: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.laser_on);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "power: ";
    Printer<float>::stream(s, indent + "  ", v.power);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MONITORING_MESSAGE_MSGSTATUS_H
