// Generated by gencpp from file camera_monitoring/MsgVelocityStatus.msg
// DO NOT EDIT!


#ifndef CAMERA_MONITORING_MESSAGE_MSGVELOCITYSTATUS_H
#define CAMERA_MONITORING_MESSAGE_MSGVELOCITYSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera_monitoring
{
template <class ContainerAllocator>
struct MsgVelocityStatus_
{
  typedef MsgVelocityStatus_<ContainerAllocator> Type;

  MsgVelocityStatus_()
    : running(false)
    , speed(0.0)  {
    }
  MsgVelocityStatus_(const ContainerAllocator& _alloc)
    : running(false)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _running_type;
  _running_type running;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::camera_monitoring::MsgVelocityStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_monitoring::MsgVelocityStatus_<ContainerAllocator> const> ConstPtr;

}; // struct MsgVelocityStatus_

typedef ::camera_monitoring::MsgVelocityStatus_<std::allocator<void> > MsgVelocityStatus;

typedef boost::shared_ptr< ::camera_monitoring::MsgVelocityStatus > MsgVelocityStatusPtr;
typedef boost::shared_ptr< ::camera_monitoring::MsgVelocityStatus const> MsgVelocityStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_monitoring::MsgVelocityStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_monitoring::MsgVelocityStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::camera_monitoring::MsgVelocityStatus_<ContainerAllocator1> & lhs, const ::camera_monitoring::MsgVelocityStatus_<ContainerAllocator2> & rhs)
{
  return lhs.running == rhs.running &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::camera_monitoring::MsgVelocityStatus_<ContainerAllocator1> & lhs, const ::camera_monitoring::MsgVelocityStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace camera_monitoring

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::camera_monitoring::MsgVelocityStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_monitoring::MsgVelocityStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_monitoring::MsgVelocityStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_monitoring::MsgVelocityStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_monitoring::MsgVelocityStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_monitoring::MsgVelocityStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_monitoring::MsgVelocityStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f12f52908a2201f7da503aef7f554966";
  }

  static const char* value(const ::camera_monitoring::MsgVelocityStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf12f52908a2201f7ULL;
  static const uint64_t static_value2 = 0xda503aef7f554966ULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_monitoring::MsgVelocityStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_monitoring/MsgVelocityStatus";
  }

  static const char* value(const ::camera_monitoring::MsgVelocityStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_monitoring::MsgVelocityStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool running\n"
"float32 speed\n"
;
  }

  static const char* value(const ::camera_monitoring::MsgVelocityStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_monitoring::MsgVelocityStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.running);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgVelocityStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_monitoring::MsgVelocityStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_monitoring::MsgVelocityStatus_<ContainerAllocator>& v)
  {
    s << indent << "running: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.running);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MONITORING_MESSAGE_MSGVELOCITYSTATUS_H
