// Generated by gencpp from file camera_monitoring/MsgVelocity.msg
// DO NOT EDIT!


#ifndef CAMERA_MONITORING_MESSAGE_MSGVELOCITY_H
#define CAMERA_MONITORING_MESSAGE_MSGVELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace camera_monitoring
{
template <class ContainerAllocator>
struct MsgVelocity_
{
  typedef MsgVelocity_<ContainerAllocator> Type;

  MsgVelocity_()
    : header()
    , speed(0.0)
    , vx(0.0)
    , vy(0.0)
    , vz(0.0)  {
    }
  MsgVelocity_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , speed(0.0)
    , vx(0.0)
    , vy(0.0)
    , vz(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _speed_type;
  _speed_type speed;

   typedef float _vx_type;
  _vx_type vx;

   typedef float _vy_type;
  _vy_type vy;

   typedef float _vz_type;
  _vz_type vz;





  typedef boost::shared_ptr< ::camera_monitoring::MsgVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_monitoring::MsgVelocity_<ContainerAllocator> const> ConstPtr;

}; // struct MsgVelocity_

typedef ::camera_monitoring::MsgVelocity_<std::allocator<void> > MsgVelocity;

typedef boost::shared_ptr< ::camera_monitoring::MsgVelocity > MsgVelocityPtr;
typedef boost::shared_ptr< ::camera_monitoring::MsgVelocity const> MsgVelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_monitoring::MsgVelocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_monitoring::MsgVelocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::camera_monitoring::MsgVelocity_<ContainerAllocator1> & lhs, const ::camera_monitoring::MsgVelocity_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.speed == rhs.speed &&
    lhs.vx == rhs.vx &&
    lhs.vy == rhs.vy &&
    lhs.vz == rhs.vz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::camera_monitoring::MsgVelocity_<ContainerAllocator1> & lhs, const ::camera_monitoring::MsgVelocity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace camera_monitoring

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::camera_monitoring::MsgVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_monitoring::MsgVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_monitoring::MsgVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_monitoring::MsgVelocity_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_monitoring::MsgVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_monitoring::MsgVelocity_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_monitoring::MsgVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a8ee6abcb387751176b04fc9ff99076";
  }

  static const char* value(const ::camera_monitoring::MsgVelocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a8ee6abcb387751ULL;
  static const uint64_t static_value2 = 0x176b04fc9ff99076ULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_monitoring::MsgVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_monitoring/MsgVelocity";
  }

  static const char* value(const ::camera_monitoring::MsgVelocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_monitoring::MsgVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 speed\n"
"float32 vx\n"
"float32 vy\n"
"float32 vz\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::camera_monitoring::MsgVelocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_monitoring::MsgVelocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.speed);
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.vz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgVelocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_monitoring::MsgVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_monitoring::MsgVelocity_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "vx: ";
    Printer<float>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<float>::stream(s, indent + "  ", v.vy);
    s << indent << "vz: ";
    Printer<float>::stream(s, indent + "  ", v.vz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MONITORING_MESSAGE_MSGVELOCITY_H
