// Generated by gencpp from file laam_laser_control/MsgPower.msg
// DO NOT EDIT!


#ifndef LAAM_LASER_CONTROL_MESSAGE_MSGPOWER_H
#define LAAM_LASER_CONTROL_MESSAGE_MSGPOWER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace laam_laser_control
{
template <class ContainerAllocator>
struct MsgPower_
{
  typedef MsgPower_<ContainerAllocator> Type;

  MsgPower_()
    : header()
    , value(0.0)  {
    }
  MsgPower_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::laam_laser_control::MsgPower_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::laam_laser_control::MsgPower_<ContainerAllocator> const> ConstPtr;

}; // struct MsgPower_

typedef ::laam_laser_control::MsgPower_<std::allocator<void> > MsgPower;

typedef boost::shared_ptr< ::laam_laser_control::MsgPower > MsgPowerPtr;
typedef boost::shared_ptr< ::laam_laser_control::MsgPower const> MsgPowerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::laam_laser_control::MsgPower_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::laam_laser_control::MsgPower_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::laam_laser_control::MsgPower_<ContainerAllocator1> & lhs, const ::laam_laser_control::MsgPower_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::laam_laser_control::MsgPower_<ContainerAllocator1> & lhs, const ::laam_laser_control::MsgPower_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace laam_laser_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::laam_laser_control::MsgPower_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laam_laser_control::MsgPower_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laam_laser_control::MsgPower_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laam_laser_control::MsgPower_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laam_laser_control::MsgPower_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laam_laser_control::MsgPower_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::laam_laser_control::MsgPower_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4bea522f9243fd34ea7bc74ce85697a8";
  }

  static const char* value(const ::laam_laser_control::MsgPower_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4bea522f9243fd34ULL;
  static const uint64_t static_value2 = 0xea7bc74ce85697a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::laam_laser_control::MsgPower_<ContainerAllocator> >
{
  static const char* value()
  {
    return "laam_laser_control/MsgPower";
  }

  static const char* value(const ::laam_laser_control::MsgPower_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::laam_laser_control::MsgPower_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# the power to be published and send to laser socket\n"
"Header header\n"
"float32 value\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::laam_laser_control::MsgPower_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::laam_laser_control::MsgPower_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgPower_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::laam_laser_control::MsgPower_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::laam_laser_control::MsgPower_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "value: ";
    Printer<float>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAAM_LASER_CONTROL_MESSAGE_MSGPOWER_H
